services:
  # === MySQL ===
  db:
    image: mysql:8.0
    container_name: cloudklp2_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456789"
      MYSQL_DATABASE: "cloud_storage"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # == S3 MinIO ===
  minio:
    image: minio/minio
    container_name: cloudklp2_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: "cloudklp2_admin"
      MINIO_ROOT_PASSWORD: "123456789"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  mysql_data:
  minio_data: